# Generated by Django 3.2.9 on 2021-12-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizing_events', to='levelupapi.gamer'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='No time selected', max_length=5),
        ),
    ]
