# Generated by Django 3.2.9 on 2022-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
